# Site settings
title: Mohammad Tohidi's CV
description: Mohammad Tohidi's CV
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: "Mohamad Tohidi"
user_title: "Deep Learning Engineer"
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
email: the.mohammad.tohidi@gmail.com
github_username:  mohamad-tohidi

collections:
  projects:
    output: true
    permalink: /projects/:title/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
